language: php
php:
  - 5.5
  - 5.6
  - hhvm
  - nightly
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install
script:
  - ./vendor/bin/phpunit
  - if [ "$(php --version | grep 'PHP 5.6')" != "" ]; then ./vendor/bin/coveralls -v; fi
